### ISSUE TITLE
Twitter's new API changes causes tool to malfunction; JSONDecodeError When Attempting to Download a Twitter Space

### ISSUE THREAD

**Issue by pretyflaco** [HoloArchivists/tslazer#6] opened 2023-07-03 15:37 UTC
Hello,

I've been trying to use the tslazer program to download a Twitter Space using the following command:

`python3 tslazer.py --space_id 1ynJOaBDloEKR --fileformat %St_%Ud`

However, I'm encountering an issue where I receive a `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` error. This error suggests that the program is receiving an empty response when trying to fetch metadata for the Twitter Space.

Here is the full traceback for reference:

```
Traceback (most recent call last):
File "/home/kasita/Downloads/tslazer/tslazer.py", line 39, in <module>
TwitterSpace.TwitterSpace(space_id=args.space_id, filenameformat=args.fileformat, path=args.path, withChat=args.withchat)
File "/home/kasita/Downloads/tslazer/TwitterSpace.py", line 251, in init
self.metadata = TwitterSpace.getMetadata(self.space_id, guest_token)
File "/home/kasita/Downloads/tslazer/TwitterSpace.py", line 128, in getMetadata
metadataResponse = metadataRequest.json()
File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by BakungaBronson** [comment] 2023-07-03 15:39
Same. I was reading through the code just now. @ef1500 could it be because of the way the guest token is acquired?

**Comment by ef1500** [comment] 2023-07-04 18:23
Hello! 

This error usually gets thrown when a twitter space is already over and you attempt to grab it by ID after it has already ended.

Can you verify that the program still works with another space ID?

**Comment by pretyflaco** [comment] 2023-07-04 23:46
Wait. I thought the purpose of the tool was to download audio file of a recorded twitter space after it ended. Did I misunderstand?

**Comment by ef1500** [comment] 2023-07-06 15:34
That is indeed its purpose. Unfortunately, due to new API limitations, the entire tool's functionality is now broken. I have now addressed this in the readme. 

Any and all help is welcomed appreciated.

**Comment by ef1500** [comment] 2023-07-10 01:07
This issue has been fixed in the most recent commit. Please update the tool and let me know if it works now :)

**Comment by pretyflaco** [comment] 2023-07-10 16:28
Updated, I get the following error:
`NameError: name 'self' is not defined`

**Comment by ef1500** [comment] 2023-07-10 17:51
I'm unable to reproduce the issue on a freshly cloned version of the tool. Everything functions properly now.
![2023-07-10_11-49](https://github.com/HoloArchivists/tslazer/assets/45581646/b68f4fa2-87d7-4e66-9ef0-dac6c7384b5a)

**Closed as not planned** 2023-07-10 17:52 UTC
Labels: help wanted
